name: flutter_application_1
description: "AI Voice Generator using ElevenLabs API"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons (iOS styled)
  cupertino_icons: ^1.0.8

  # HTTP requests (for ElevenLabs API calls)
  http: ^1.2.2

  # Audio player (play generated voice)
  audioplayers: ^6.1.0

  # State management
  provider: ^6.1.2

  # Google Fonts (premium look UI)
  google_fonts: ^6.2.1

  # File picker (optional if you want user to upload audio/video later)
  file_picker: ^8.0.6

  # 🔑 For environment variables (API keys safely store)
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/
  assets:
    - .env
